src/Entity/ProduitPlat.php
<?php

namespace App\Entity;

use App\Repository\ProduitPlatRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass=ProduitPlatRepository::class)
 */
class ProduitPlat
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id_produitplat;

    /**
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id_categorie;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="le nom du plat ou du boisson est obligatoire")
     *  @Assert\Length(
     *      min = 3,
     *      max = 30,
     *      minMessage = "Le nombre de caractére minimal est {{ limit }}",
     *      maxMessage = "Le nombre de caractére maximal est {{ limit }} "
     * )
     * @Groups("post:read")
     */
    private $nom_produitplat;

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive
     * @Assert\NotBlank(message="le prix est obligatoire")
     * @Groups("post:read")
     */
    private $prix;

    public function getIdProduitPlat(): ?int
    {
        return $this->id_produitplat;
    }

    public function getIdCategorie(): ?int
    {
        return $this->id_categorie;
    }

    public function setIdCategorie(int $id_categorie): self
    {
        $this->id_categorie = $id_categorie;

        return $this;
    }

    public function getNomProduitplat(): ?string
    {
        return $this->nom_produitplat;
    }

    public function setNomProduitplat(string $nom_produitplat): self
    {
        $this->nom_produitplat = $nom_produitplat;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

     //    Relations

    /**
     * @ORM\ManyToMany(targetEntity=Restaurant::class, mappedBy="produitplats", cascade={"persist"})
     * @ORM\JoinColumn(name="id_restaurant", referencedColumnName="id_restaurant")
     *
     *
     */
    private $restaurants;

    public function __construct()
    {
        $this->restaurants = new ArrayCollection();
    }


    /**
     * @return Collection|Restaurant[]|null
     */
    public function getRestaurants(): Collection
    {
        return $this->restaurants;
    }
  /*  public function setRestaurants(?Restaurant $restaurants): self
    {
        $this->restaurants = $restaurants;

        return $this;
    }*/


    public function addRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurants->contains($restaurant))
        {
            $this->restaurants[] = $restaurant;
            $restaurant->addProduitPlat($this);
        }

        return $this;
    }

    public function removeRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurants->contains($restaurant)) {
            $restaurant->removeProduitPlat($this);
        }
        return $this;

    }


    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="produitplats")
     * @ORM\JoinColumns({
     *  @ORM\JoinColumn(name="id_categorie", referencedColumnName="id_categorie" , onDelete="CASCADE")
     * })
     *
     *
     */
    private $categories;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("post:read")
     */
    private $desc_produitplat;
    public function getCategories(): ?Categorie
    {
        return $this->categories;
    }

    public function setCategories(?Categorie $categories): self
    {
        $this->categories = $categories;

        return $this;
    }

    public function getDescProduitplat(): ?string
    {
        return $this->desc_produitplat;
    }

    public function setDescProduitplat(?string $desc_produitplat): self
    {
        $this->desc_produitplat = $desc_produitplat;

        return $this;
    }




}

src/Form/ProduitPlatType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\ProduitPlat;
use App\Entity\Restaurant;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitPlatType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
//            ->add('id_categorie')
            ->add('nom_produitplat')
            ->add('desc_produitplat')
            ->add('prix')
            /*->add('restaurants',
                EntityType::class,[
                    'class' => Restaurant::class,
                    'choice_label' => 'nom_restaurant',
                ])*/
            ->add('categories',
                EntityType::class,[
                    'class' => Categorie::class,
                    'choice_label' => 'nom_categorie',
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => ProduitPlat::class,
        ]);
    }
}

src/Controller/ProduitPlatController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\ProduitPlat;
use App\Entity\Restaurant;
use App\Form\ProduitPlatType;
use App\Repository\ProduitPlatRepository;
use App\Repository\CategorieRepository;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

/**
 * @Route("/produit/plat")
 */
class ProduitPlatController extends AbstractController
{
    /**
     * @Route("/finAll", name="produit_plat_index", methods={"GET"})
     */
    public function index(ProduitPlatRepository $produitPlatRepository): Response
    {
        return $this->render('Back/produit_plat/index.html.twig', [
            'produit_plats' => $produitPlatRepository->findAll(),
        ]);
    }

    /**
     * @Route("/aff/{id_restaurant}/{id_categorie}", name="JsonProduitPlatCategorie")
     */
    public function JsonPDT(Categorie $categorie,NormalizerInterface $normalizer,Restaurant $res, Request $request):Response
    {   $resid=$res->getIdRestaurant();
        $categorie2 = $this->getDoctrine()->getRepository(Categorie::class)->findCategorie($resid);
        $id=$categorie->getIdCategorie();
        $donnees= $this->getDoctrine()->getRepository(ProduitPlat::class)->findProduitPlatByCategorieandRestaurant($resid,$id);
        $res->getProduitPlats();
        $js=$normalizer->normalize($donnees,'json',['groups'=>'post:read']);
        return new Response(json_encode($js));

    }


    /**
     * @Route("/new", name="produit_plat_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produitPlat = new ProduitPlat();
        $form = $this->createForm(ProduitPlatType::class, $produitPlat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produitPlat);
            $entityManager->flush();

            return $this->redirectToRoute('produit_plat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('Back/produit_plat/new.html.twig', [
            'produit_plat' => $produitPlat,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/stat", name="stat", methods={"GET"})
     */
    public function stat(CategorieRepository $categorieRepo): Response
    {    $categories = $categorieRepo->findAll();

        $categNom = [];
        $categCount = [];

        // On "démonte" les données pour les séparer tel qu'attendu par ChartJS
        foreach($categories as $categorie){
            $categNom[] = $categorie->getNomCategorie();
            $categCount[] = count($categorie->getProduitPlats());
        }
        return $this->render('Back/produit_plat/Graph.html.twig', [
            'categNom' => json_encode($categNom),
            'categCount' => json_encode($categCount),
        ]);
    }


    /**
     * @Route("/{id_produitplat}", name="produit_plat_show", methods={"GET"})
     */
    public function show(ProduitPlat $produitPlat): Response
    {
        return $this->render('Back/produit_plat/show.html.twig', [
            'produit_plat' => $produitPlat,
        ]);
    }

    /**
     * @Route("/showpdtCAT/{id_restaurant}/{id_categorie}", name="showProduitPlatCategorie", methods={"GET"})
     */
    public function showPDT(Categorie $categorie,PaginatorInterface $paginator,Restaurant $res, Request $request):Response
    {   $resid=$res->getIdRestaurant();
        $categorie2 = $this->getDoctrine()->getRepository(Categorie::class)->findCategorie($resid);
        $id=$categorie->getIdCategorie();
        $donnees= $this->getDoctrine()->getRepository(ProduitPlat::class)->findProduitPlatByCategorieandRestaurant($resid,$id);
        $listPdt = $paginator->paginate(
            $donnees,
            $request->query->getInt('page', 1),
            5
        );
        $res->getProduitPlats();
        return $this->render('Front/MenuCategorie.html.twig', [
            "restaurant"=>$res,
            "categorie"=>$categorie2,
            "listPdt"=>$listPdt]);
    }



    /**
     * @Route("/{id_produitplat}/edit", name="produit_plat_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, ProduitPlat $produitPlat, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitPlatType::class, $produitPlat);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('produit_plat_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('Back/produit_plat/edit.html.twig', [
            'produit_plat' => $produitPlat,
            'form' => $form->createView(),
        ]);
    }





    /**
     * @Route("/{id_produitplat}", name="produit_plat_delete", methods={"POST"})
     */
    public function delete(Request $request, ProduitPlat $produitPlat, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produitPlat->getIdProduitPlat(), $request->request->get('_token'))) {
            $entityManager->remove($produitPlat);
            $entityManager->flush();
        }

        return $this->redirectToRoute('produit_plat_index', [], Response::HTTP_SEE_OTHER);
    }



}

templates/Back/produit_plat/Graph.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Graph {% endblock %}

{% block bodyBack %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.css" integrity="sha512-/zs32ZEJh+/EO2N1b0PEdoA10JkdC3zJ8L5FTiQu82LR9S/rOQNfQN7U59U9BC12swNeRAz3HSzIL2vpp4fv3w==" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js" integrity="sha512-s+xg36jbIujB2S2VKfpGmlC3T5V2TF3lY48DX7u2r9XzGzgPsa6wTpOQA7J9iffvdeBN0q9tKzRxVxw1JviZPg==" crossorigin="anonymous"></script>
    <div class="card">
        <h2>Nombre de produits par catégorie</h2>
        <canvas id="categories" width="400" height="100"></canvas>
    </div>

<script>
    let categories = document.querySelector("#categories")
    let categGraph = new Chart(categories, {
        type: "doughnut",
        data: {
            labels: {{ categNom|raw }},
            datasets: [{
                label: "Répartition des catégories",
                data: {{ categCount|raw }},
                backgroundColor: ["blue","pink","orange"],
            }]
        }
    })
    </script>

{% endblock %}

templates/Back/produit_plat/_delete_form.html.twig
<form method="post" action="{{ path('produit_plat_delete', {'id_produitplat': produit_plat.getIdProduitPlat()}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit_plat.getIdProduitPlat()) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/Back/produit_plat/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate' , 'class':'form-horizontal'}}) }}
<div class="form-group">

    <h5 class="text-danger">    {{ form_errors(form.nom_produitplat) }}</h5>
    {{ form_label(form.nom_produitplat,"Nom du plat ou boissons") }}
    {{ form_widget(form.nom_produitplat ,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">

    <h5 class="text-danger">  {{ form_errors(form.desc_produitplat) }}</h5>
    {{ form_label(form.desc_produitplat,"Introduisez les ingrediants") }}
    {{ form_widget(form.desc_produitplat ,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    <h5 class="text-danger">  {{ form_errors(form.prix) }}</h5>
    {{ form_label(form.prix,"Prix") }}
    {{ form_widget(form.prix,{'attr': {'class': 'form-control'}})  }}
</div>
<div class="form-group">
    <h5 class="text-danger">  {{ form_errors(form.categories) }}</h5>
    {{ form_label(form.categories,"la categorie relative") }}
    {{ form_widget(form.categories,{'attr': {'class': 'form-control'}})  }}
</div>

<div class="col-md-12 text-center">
    <button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>

</div>


{{ form_end(form) }}

templates/Back/produit_plat/edit.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Modifier ProduitPlat{% endblock %}

{% block bodyBack %}

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Modifier un produit </h3>
                        </div>
                        <!-- /.card-header -->
                        <!-- form start -->

                        <div class="card-body">

                            {{ include('Back/produit_plat/_form.html.twig', {'button_label': 'Modifier'}) }}
                        </div>
                        <div class="card-body">
                            {{ include('Back/produit_plat/_delete_form.html.twig') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>






    <a href="{{ path('produit_plat_index') }}">Retour à la liste</a>

    {{ include('Back/produit_plat/_delete_form.html.twig') }}
{% endblock %}

templates/Back/produit_plat/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Liste des Produits/Plats {% endblock %}

{% block bodyBack %}
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Table Plats/Boissons</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <div class="row">
                <div class="col-sm-12 col-md-6">

                </div>
            </div>
        <thead>
            <tr>
                <th>Id_produitplat</th>
                <th>Id_categorie</th>
                <th>Nom_produitplat</th>
                <th>Prix</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit_plat in produit_plats %}
            <tr>
                <td>{{ produit_plat.idProduitplat }}</td>
                <td>{{ produit_plat.idCategorie }}</td>
                <td>{{ produit_plat.nomProduitplat }}</td>
                <td>{{ produit_plat.prix }}</td>
                <td>
                    <a class="btn btn-info" href="{{ path('produit_plat_show', {'id_produitplat': produit_plat.getIdProduitPlat()}) }}">Afficher</a>
                    <a class="btn btn-secondary" href="{{ path('produit_plat_edit', {'id_produitplat': produit_plat.getIdProduitPlat()}) }}">Modifier</a>
                    {{ include('Back/produit_plat/_delete_form.html.twig' , {'button_label': 'Delete'}) }}



                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
        </table>
    </div>
    <!-- /.card-body -->
</div>
    <!-- /.card -->


{% endblock %}

templates/Back/produit_plat/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Ajouter un ProduitPlat{% endblock %}

{% block bodyBack %}
    <div class="content-wrapper">
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Ajouter un plat ou boisson</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                    <div class="card-body">

    {{ include('Back/produit_plat/_form.html.twig') }}
                        </div>


                </div>
            </div>
        </div>
    </div>
</section>
    </div>

    <a href="{{ path('produit_plat_index') }}">Retour a la liste</a>
{% endblock %}

templates/Back/produit_plat/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Boisson / Plat{% endblock %}

{% block bodyBack %}
    <h1>Plats / Boissons</h1>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Table Plats/Boissons</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table id="example1" class="table table-bordered table-striped">
            <div class="row">
                <div class="col-sm-12 col-md-6">

                </div>
            </div>
        <tbody>
            <tr>
                <th>Id_produitplat</th>
                <td>{{ produit_plat.idProduitplat }}</td>
            </tr>
            <tr>
                <th>Id_categorie</th>
                <td>{{ produit_plat.idCategorie }}</td>
            </tr>
            <tr>
                <th>Nom_produitplat</th>
                <td>{{ produit_plat.nomProduitplat }}</td>
            </tr>
            <tr>
                <th>Prix</th>
                <td>{{ produit_plat.prix }}</td>
            </tr>
        </tbody>
    </table>
    </div>
</div>
    <div class="col-md-12 text-center">
        <a class="btn btn-outline-dark" href="{{ path('produit_plat_index') }}">Liste des plats/boissons</a>
    </div>
{% endblock %}