src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;


/**
 * @ORM\Entity(repositoryClass=RestaurantRepository::class)
 */
class Restaurant
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id_restaurant;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="le nom du restaurant est obligatoire")
     *  @Assert\Length(
     *      min = 3,
     *      max = 25,
     *      minMessage = "Le nombre de caractére minimal est {{ limit }}",
     *      maxMessage = "Le nombre de caractére maximal est {{ limit }} "
     * )
     * @Groups("post:read")
     */
    private $nom_restaurant;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="la description du restaurant est obligatoire")
     * @Groups("post:read")
     */
    private $desc_restaurant;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive(message="La capacité doit etre une valeur positive")
     * @Assert\NotBlank(message="vous devez inserer le nombre de place de votre restaurant")
     * * @Assert\Range(
     *      min = 1,
     *      max = 50,
     *      notInRangeMessage = "la capacite du restaurant doit etre entre {{ min }} et {{ max }}",
     * )
     * @Groups("post:read")
     */
    private $capacite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Length(
     *      min = 8,
     *      max = 8,
     *      minMessage = "le numero du telephone doit contenir 8 numeros",
     *      maxMessage = "le numero du telephone doit contenir 8 numeros"
     * )
     *@Assert\NotBlank(message="le numero de telephone est obligatoire")
     * @Assert\Positive
     * @Groups("post:read")
     */
    private $num_tel;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Groups("post:read")
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotBlank(message="vous devez choisir la sepcialite de votre restaurant")
     * @Groups("post:read")
     */
    private $specialite;

   
    /**
     * @ORM\OneToMany(targetEntity=OffreTravail::class, mappedBy="restaurant")
     *
     *
     */
    private $offreTravail;

    public function __construct()
    {
        $this->offreTravail = new ArrayCollection();
        $this->produitplats = new ArrayCollection();

    }

    public function getIdRestaurant(): ?int
    {
        return $this->id_restaurant;
    }

    public function getNomRestaurant(): ?string
    {
        return $this->nom_restaurant;
    }

    public function setNomRestaurant(string $nom_restaurant): self
    {
        $this->nom_restaurant = $nom_restaurant;

        return $this;
    }

    public function getDescRestaurant(): ?string
    {
        return $this->desc_restaurant;
    }

    public function setDescRestaurant(string $desc_restaurant): self
    {
        $this->desc_restaurant = $desc_restaurant;

        return $this;
    }

    public function getCapacite(): ?int
    {
        return $this->capacite;
    }

    public function setCapacite(int $capacite): self
    {
        $this->capacite = $capacite;

        return $this;
    }

    public function getNumTel(): ?string
    {
        return $this->num_tel;
    }

    public function setNumTel(?string $num_tel): self
    {
        $this->num_tel = $num_tel;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(?string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getSpecialite(): ?string
    {
        return $this->specialite;
    }

    public function setSpecialite(?string $specialite): self
    {
        $this->specialite = $specialite;

        return $this;
    }



    //    Relations

    /**
     * @ORM\ManyToMany(targetEntity=ProduitPlat::class, inversedBy="restaurants")
     *  @ORM\JoinTable(name="Resto_produitplat",
     *     joinColumns={@ORM\JoinColumn(name="id_restaurant", referencedColumnName="id_restaurant")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="id_produitplat", referencedColumnName="id_produitplat")}
     *      )
     * @Groups("post:read")
     */

    private $produitplats;

    /**
     * @return Collection|ProduitPlat[]
     */
    public function getProduitPlats(): Collection
    {
        return $this->produitplats;
    }

    public function addProduitPlat(ProduitPlat $produitplat): self
    {
        if (!$this->produitplats->contains($produitplat)) {
            $this->produitplats[] = $produitplat;
        }
        return $this;
    }



    /**
     * @return Collection|OffreTravail[]
     */
    public function getOffreTravail(): Collection
    {
        return $this->offreTravail;
    }

    public function addOffreTravail(OffreTravail $offreTravail): self
    {
        if (!$this->offreTravail->contains($offreTravail)) {
            $this->offreTravail[] = $offreTravail;
            $offreTravail->setRestaurant($this);
        }

        return $this;
    }


    public function removeProduitPlat(ProduitPlat $produitplat): self
    {
       $this->produitplats->removeElement($produitplat);

        return $this;
    }



    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="restaurants")
     *
     *
     */
    private $reservations;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="restaurants")
     * @ORM\JoinColumn(nullable=false)
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", onDelete="CASCADE")
     * })
     *
     */
    private $user;

    /**
     * @return Collection|Reservation[]|null
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setReservation($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getReservation() === $this) {
                $reservation->setReservation(null);
            }
        }
        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }


    public function removeOffreTravail(OffreTravail $offreTravail): self
    {
        if ($this->offreTravail->removeElement($offreTravail)) {
            // set the owning side to null (unless already changed)
            if ($offreTravail->getRestaurant() === $this) {
                $offreTravail->setRestaurant(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getNomRestaurant();
    }





}

src/Form/RestaurantType.php
<?php

namespace App\Form;

use App\Entity\Categorie;
use App\Entity\ProduitPlat;
use App\Entity\Restaurant;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\ChoiceList\ArrayChoiceList;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;



class RestaurantType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_restaurant')
            ->add('desc_restaurant')
            ->add('capacite')
            ->add('num_tel')
            ->add('adresse')
            ->add('specialite',ChoiceType::class, [
                'choices'  => [
                    'Tunisien' => 'Tunisien',
                    'Chinois' => 'Chinois',
                    'thailandais' => 'thailandais',
                    'Italien' => 'Italien',
                    'Libanais' => 'Libanais' ,
                ],
            ])
//            ->add('produitplats')

               /* ->add('produitplats', ChoiceType::class, [
                    'class' => ProduitPlat::class,
                    'group_by' => ChoiceList::groupBy($this, 'id_categorie'),
                ])*/


            ->add('produitplats',
                EntityType::class,[
                    'class' => ProduitPlat::class,
                    'choice_label' => 'nom_produitplat',
                    'group_by' => function(ProduitPlat $pdt) {
                        return $pdt->getCategories()->getNomCategorie();
                    },
                    'expanded'=>'true',
                    'multiple'=>'true',
                ])


        ;


    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Restaurant::class,
        ]);
    }
}

src/Controller/RestaurantController.php
<?php

namespace App\Controller;

use App\Entity\Categorie;
use App\Entity\User;
use App\Entity\ProduitPlat;
use App\Entity\Restaurant;
use App\Form\RestaurantType;
use App\Repository\RestaurantRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use phpDocumentor\Reflection\DocBlock\Serializer;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\Serializer\Annotation\SerializedName;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;


/**
 * @Route("/restaurant")
 */
class RestaurantController extends AbstractController
{

    /**
     * @Route("/listjson", name="restaurant_json")
     */
    public function ListRestaurantJson(RestaurantRepository $restaurep, NormalizerInterface $normalizer): Response
    {
        $restaurant=$restaurep->findAll();
        $js=$normalizer->normalize($restaurant,'json',['groups'=>'post:read']);
       // $json=$serializerinterface->normalize($restaurant,'json',['groups'=>'restaurant']);
       // dump($restaurant);
        //die;
       //$formatted= $serializer->normalize($json);
        return new Response(json_encode($js));
    }


    /**
     * @Route("/findAll", name="restaurant_index", methods={"GET"})
     */
    public function index(RestaurantRepository $restaurantRepository): Response
    {
        return $this->render('Back/restaurant/index.html.twig', [
            'restaurants' => $restaurantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/{id_restaurant}/affCat", name="CategorieRestaurant")
     */
    public function ListRestaurantCategorie(Restaurant $restaurant,NormalizerInterface $normalizer): Response
    {
        $resid=$restaurant->getIdRestaurant();
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->findCategorie($resid);
        $js=$normalizer->normalize($categorie,'json',['groups'=>'post:read']);
        return new Response(json_encode($js));
    }

    /**
     * @Route("/new", name="restaurant_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {
        $restaurant = new Restaurant();

        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $em = $this->getDoctrine()->getManager();
            foreach ($form['produitplats']->getData()->getValues() as $v) {
                $produitplats = $em->getRepository(ProduitPlat::class)->find($v->getIdProduitPlat());
                if ($produitplats) {
                    $produitplats->addRestaurant($restaurant);
                }
            }
            $UserId=35; // hethy twali b session
            $User=$userRepository->find($UserId);
           // $restaurant->setIdClient($UserId);
            $restaurant->setUser($User);
            $entityManager->persist($restaurant);
            $entityManager->flush();
            return $this->redirectToRoute('restaurant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('Back/restaurant/new.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/liste", name="restaurant_liste", methods={"GET"})
     */
    public function index2(Request $request, PaginatorInterface $paginator): Response
    {

        $donnees = $this->getDoctrine()->getRepository(Restaurant::class)->findAll();

        $restaurants = $paginator->paginate(
            $donnees, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            6 // Nombre de résultats par page
        );

        return $this->render('/Front/listRestaurent.html.twig', [

            'restaurants' => $restaurants,
        ]);

    }
    /**
     * @Route("/detail/{id_restaurant}", name="restaurant3", methods={"GET"})
     */
    public function show3(Restaurant $restaurant): Response
    {
        $Prop=$restaurant->getUser();
        $proprio=$this->getDoctrine()->getRepository(User::class)->find($Prop);
        $nomProp=$proprio->getNom();
        return $this->render('Front/restaurent.html.twig', [
            'restaurant' => $restaurant,
            'nomProp'=>$nomProp

        ]);
    }

    /**
     * @Route("/{id_restaurant}", name="restaurant_show", methods={"GET"})
     */
    public function show(Restaurant $restaurant): Response
    {
        return $this->render('Back/restaurant/show.html.twig', [
            'restaurant' => $restaurant,

        ]);
    }






    /**
     * @Route("/{id_restaurant}/aff", name="details_menu", methods={"GET"})
     */
    public function show2(Restaurant $restaurant, PaginatorInterface $paginator, Request $request): Response
    {
        $resid=$restaurant->getIdRestaurant();
        $categorie = $this->getDoctrine()->getRepository(Categorie::class)->findCategorie($resid);
        return $this->render('/Front/menu.html.twig', [
            'restaurant'=>$restaurant,
            'categorie'=>$categorie,
        ]);
    }




    /**
     * @Route("/{id_restaurant}/edit", name="restaurant_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Restaurant $restaurant,EntityManagerInterface $entityManager): Response
    {
        //$restaurant->getProduitPlats();
        $form = $this->createForm(RestaurantType::class, $restaurant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('restaurant_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->render('Back/restaurant/edit.html.twig', [
            'restaurant' => $restaurant,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id_restaurant}", name="restaurant_delete", methods={"POST"})
     */
    public function delete(Request $request, Restaurant $restaurant, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$restaurant->getIdRestaurant(), $request->request->get('_token'))) {
            $entityManager->remove($restaurant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('restaurant_index', [], Response::HTTP_SEE_OTHER);
    }


    /**
     * @Route("/back/GestionRestaurant", name="GestionRestaurant")
     */
    public function btn_GestionRestaurant(): Response
    {
        return $this->render('/Back/Gestion Restaurant/GestionRestaurant.html.twig', [
            'controller_name' => 'RestaurantController',
        ]);
    }




}

templates/Back/restaurant/_delete_form.html.twig
<form method="post" action="{{ path('restaurant_delete', {'id_restaurant': restaurant.getIdRestaurant()}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurant.getIdRestaurant()) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

templates/Back/restaurant/_form.html.twig
{{ form_start(form,{'attr': {'novalidate': 'novalidate' , 'class':'form-horizontal'}}) }}

<h1> Restaurant </h1>
<div class="form-group">
    <h5 class="text-danger"> {{ form_errors(form.nom_restaurant) }}</h5>

{{ form_label(form.nom_restaurant,"Nom du restaurant") }}
{{ form_widget(form.nom_restaurant ,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    <h5 class="text-danger">  {{ form_errors(form.desc_restaurant) }}</h5>


{{ form_label(form.desc_restaurant,"la Description du restaurant") }}
{{ form_widget(form.desc_restaurant,{'attr': {'class': 'form-control'}})  }}
</div>
<div class="form-group">
    <h5 class="text-danger">    {{ form_errors(form.capacite) }}</h5>
{{ form_label(form.capacite,"la capacite du restaurant") }}
{{ form_widget(form.capacite,{'attr': {'class': 'form-control'}})  }}
</div>
<div class="form-group">
    <h5 class="text-danger"> {{ form_errors(form.num_tel) }}</h5>

{{ form_label(form.num_tel,"le numero du telephone ") }}
{{ form_widget(form.num_tel ,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    <h5 class="text-danger"> {{ form_errors(form.adresse) }}</h5>
{{ form_label(form.adresse,"l'adresse") }}
{{ form_widget(form.adresse ,{'attr': {'class': 'form-control'}}) }}
</div>
<div class="form-group">
    <h5 class="text-danger"> {{ form_errors(form.specialite) }}</h5>
{{ form_label(form.specialite,"la specialite")}}
{{ form_widget(form.specialite ,{'attr': {'class': 'form-control'}}) }}
</div>






<div class="container-fluid">
    <div class="checkbox">
    <h5 class="text-danger"> {{ form_errors(form.produitplats) }}</h5>
    {{ form_label(form.produitplats,"Composez votre menu",{'attr': {'class': 'label label-primary'}})}}
    {{ form_widget(form.produitplats ,{'attr': {'class': 'form-check-input position-static'}}) }}
</div>
</div>
<div class="col-md-12 text-center">
    <button class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>

</div>
{{ form_end(form) }}

templates/Back/restaurant/edit.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Modifier Restaurant{% endblock %}

{% block bodyBack %}

<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h2 class="card-title">Modifier Un Restaurant </h2>
                        </div>
                        <!-- /.card-header -->


                        <div class="card-body">

                            {{ include('Back/restaurant/_form.html.twig', {'button_label': 'Modifier'}) }}


                        </div>


                    </div>
                </div>
            </div>
        </div>
    </section>
</div>



{% endblock %}

templates/Back/restaurant/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Liste des Restaurants {% endblock %}

{% block bodyBack %}

    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Liste des restaurants</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table id="example1" class="table table-bordered table-striped">
                <div class="row">
                    <div class="col-sm-12 col-md-6">

                        </div>
                    </div>

                <thead>
                <tr>
                    <th>Id_restaurant</th>
                    <th>Nom_restaurant</th>
                    <th>Desc_restaurant</th>
                    <th>Capacite</th>
                    <th>Num_tel</th>
                    <th>Adresse</th>
                    <th>Specialite</th>
                    <th>actions</th>
                </tr>
                </thead>
                <tbody>

                {% for restaurant in restaurants %}
                <tr>
                    <td>{{ restaurant.idRestaurant }}</td>
                    <td>{{ restaurant.nomRestaurant }}</td>
                    <td>{{ restaurant.descRestaurant }}</td>
                    <td>{{ restaurant.capacite }}</td>
                    <td>{{ restaurant.numTel }}</td>
                    <td>{{ restaurant.adresse }}</td>
                    <td>{{ restaurant.specialite }}</td>
                    <td>
                        <a class="btn btn-info" href="{{ path('restaurant_show', {'id_restaurant': restaurant.getIdRestaurant()}) }}">Afficher</a>
                        <a class="btn btn-secondary" href="{{ path('restaurant_edit', {'id_restaurant': restaurant.getIdRestaurant()}) }}">Modifier</a>
                        {{ include('Back/restaurant/_delete_form.html.twig' , {'button_label': 'Delete'}) }}

                    </td>
                {% else %}
                    <tr>
                        <td colspan="6">no records found</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>
        </div>
        <!-- /.card-body -->
    </div>
    <!-- /.card -->




{% endblock %}

templates/Back/restaurant/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Ajouter Restaurant{% endblock %}

{% block bodyBack %}
    <div class="content-wrapper">
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-6">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Ajouter un restaurant</h3>
                    </div>
                    <!-- /.card-header -->
                    <!-- form start -->

                        <div class="card-body">

    {{ include('Back/restaurant/_form.html.twig') }}
                            </div>
                </div>
            </div>
        </div>
    </div>
  </section>
    </div>


    <a class="btn btn-light" href="{{ path('restaurant_index') }}">Retour a la liste</a>
{% endblock %}

templates/Back/restaurant/show.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Restaurant{% endblock %}

{% block bodyBack %}


    <h1>Restaurant</h1>

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Liste des restaurants</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">

        <table id="example1" class="table table-bordered table-striped">
            <div class="row">
                <div class="col-sm-12 col-md-6">

                </div>
            </div>
        <tbody>
            <tr>
                <th>Id_restaurant</th>
                <td>{{ restaurant.idRestaurant }}</td>
            </tr>
            <tr>
                <th>Nom_restaurant</th>
                <td>{{ restaurant.nomRestaurant }}</td>
            </tr>
            <tr>
                <th>Desc_restaurant</th>
                <td>{{ restaurant.descRestaurant }}</td>
            </tr>
            <tr>
                <th>Capacite</th>
                <td>{{ restaurant.capacite }}</td>
            </tr>
            <tr>
                <th>Num_tel</th>
                <td>{{ restaurant.numTel }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ restaurant.adresse }}</td>
            </tr>
            <tr>
                <th>Specialite</th>
                <td>{{ restaurant.specialite }}</td>
            </tr>
        </tbody>
    </table>
    </div>
</div>
<div class="col-md-12 text-center">
    <a class="btn btn-outline-dark" href="{{ path('restaurant_index') }}">Liste des restaurants</a>
</div>

{% endblock %}