src/Entity/Categorie.php
<?php

namespace App\Entity;

use App\Repository\CategorieRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;
/**
 * @ORM\Entity(repositoryClass=CategorieRepository::class)
 */
class Categorie
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id_categorie;

    /**
     * @ORM\Column(type="string", length=255)
     *@Assert\NotBlank(message="le nom de la categorie est obligatoire")
     * @Assert\Length(
     *      min = 3,
     *      max = 20,
     *      minMessage = "Le nombre de caractére minimal est {{ limit }}",
     *      maxMessage = "Le nombre de caractére maximal est {{ limit }} "
     * )
     * @Groups("post:read")
     */
    private $nom_categorie;

    public function getIdCategorie(): ?int
    {
        return $this->id_categorie;
    }

    public function getNomCategorie(): ?string
    {
        return $this->nom_categorie;
    }

    public function setNomCategorie(string $nom_categorie): self
    {
        $this->nom_categorie = $nom_categorie;

        return $this;
    }

    /*Relation*/

    /**
     * @ORM\OneToMany(targetEntity=ProduitPlat::class, mappedBy="categories")
     * @Groups("post:read")
     */
    private $produitplats;
    public function __construct()
    {
        $this->produitplats = new ArrayCollection();
    }

    /**
     * @return Collection|ProduitPlat[]|null
     */
    public function getProduitPlats(): Collection
    {
        return $this->produitplats;
    }

    public function addProduitPlat(ProduitPlat $produitplat): self
    {
        if (!$this->produitplats->contains($produitplat)) {
            $this->produitplats[] = $produitplat;
            $produitplat->setCategories($this);
        }

        return $this;
    }

        public function removeProduitPlat(ProduitPlat $produitplat): self
    {
        if ($this->produitplats->removeElement($produitplat)) {
            // set the owning side to null (unless already changed)
            if ($produitplat->getCategories() === $this) {
                $produitplat->setCategories(null);
            }
        }

        return $this;
    }
    public function __toString()
    {
        return(string)$this->getNomCategorie();
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez insérer votre nom.")
     * @Groups("post:read")
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez insérer votre prénom.")
     * @Groups("post:read")
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     * @Assert\NotBlank(message="Vous devez insérer date.")
     * @Groups("post:read")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="This value should not be blank.")
     * @Groups("post:read")
     */
    private $sexe;

    /**
     * @ORM\Column(type="integer")
     * @Assert\Positive
     * @Assert\NotBlank(message="Vous devez insérer votre numéro de téléphone.")
     * * @Assert\Length(
     *      min = 8,
     *      max = 11,
     *      minMessage = "Your user phone number must be at least {{ limit }}  long",
     *      maxMessage = "Your  phone number cannot be longer than {{ limit }} "
     * )
     * @Groups("post:read")
     */
    private $numero_tele;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez insérer votre email.")
     *  @Assert\Email(
     *     message="This email '{{ value }}' is not a valid email address.")
     * @Groups("post:read")
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];



    /**
     * @ORM\OneToMany(targetEntity=OffreTravail::class, mappedBy="user")
     */
    private $offreTravail;



    /**
     * @ORM\Column(type="string", length=255)
     * @var string The hashed password
     * @Assert\NotBlank(message="Vous devez insérer votre mot de passe!.")
     * @Groups("post:read")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\OneToMany(targetEntity=Reservation::class, mappedBy="user")
     */
    private $reservations;

    /**
     * @ORM\OneToMany(targetEntity=Restaurant::class, mappedBy="user")
     */
    private $restaurants;

    public function __construct()
    {
        $this->reservations = new ArrayCollection();
        $this->restaurants = new ArrayCollection();
        $this->offreTravail = new ArrayCollection();
    }



    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activationToken;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $resetToken;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\File()
     * @Groups("post:read")
     */
    private $image;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     *
     */
    private $address;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }


    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getNumeroTele(): ?int
    {
        return $this->numero_tele;
    }

    public function setNumeroTele(int $numero_tele): self
    {
        $this->numero_tele = $numero_tele;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getRoles(): ?array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @return Collection|offreTravail[]
     */
    public function getOffreTravail(): Collection
    {
        return $this->offreTravail;
    }

    public function addOffreTravail(offreTravail $offreTravail): self
    {
        if (!$this->offreTravail->contains($offreTravail)) {
            $this->offreTravail[] = $offreTravail;
            $offreTravail->setUser($this);
        }

        return $this;
    }

    public function removeOffreTravail(offreTravail $offreTravail): self
    {
        if ($this->offreTravail->removeElement($offreTravail)) {
            // set the owning side to null (unless already changed)
            if ($offreTravail->getUser() === $this) {
                $offreTravail->setUser(null);
            }
        }

        return $this;
    }



    public function __toString()
    {
        // TODO: Implement __toString() method.
        return $this->getEmail();

    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }


    public function getSalt()
    {
        // TODO: Implement getSalt() method.
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.

        return $this->email;
    }

    public function eraseCredentials()
    {
        // TODO: Implement eraseCredentials() method.
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }


    /**
     * @return Collection|Reservation[]
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations[] = $reservation;
            $reservation->setUser($this);
        }
        return $this;
    }


    public function getActivationToken(): ?string
    {
        return $this->activationToken;
    }

    public function setActivationToken(?string $activationToken): self
    {
        $this->activationToken = $activationToken;

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getUser() === $this) {
                $reservation->setUser(null);
            }
        }

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    /**
     * @return Collection|Restaurant[]
     */
    public function getRestaurants(): Collection
    {
        return $this->restaurants;
    }

    public function addRestaurant(Restaurant $restaurant): self
    {
        if (!$this->restaurants->contains($restaurant)) {
            $this->restaurants[] = $restaurant;
            $restaurant->setUser($this);
        }

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }


    public function removeRestaurant(Restaurant $restaurant): self
    {
        if ($this->restaurants->removeElement($restaurant)) {
            // set the owning side to null (unless already changed)
            if ($restaurant->getUser() === $this) {
                $restaurant->setUser(null);
            }
        }

        return $this;
    }





    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(?string $address): self
    {
        $this->address = $address;

        return $this;
    }

}

templates/Front/ErreurBooking.html.twig
{% extends 'base.html.twig' %}
{% block bodyMenu %}

<!-- Page Header Start -->
<div class="page-header mb-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Nos restaurants</h2>
            </div>
            <div class="col-12">
                <a href="">Accueil</a>
                <a href="">Reservation</a>
            </div>
        </div>
    </div>
</div>
    <div class="booking">
    <div class="container-fluid">
    <div class="row align-items-center">
    <div class="col-lg-7">
        <div class="booking-content">
     <h1> Ce restaurant est déja complet </h1>
            <a href="{{ path("reservation_new") }}" class="btn custom-btn"> Retour à la page </a>
        </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/Front/MenuCategorie.html.twig
{%extends '/Front/menu.html.twig'  %}
{% block DetailMenu %}

    <div class="tab-content">
        <div id="burgers" class="container tab-pane active">
            <div class="row">

                <div class="col-lg-7 col-md-12">
                    {% for pdt in listPdt %}
                        <div class="menu-item">
                            <div class="menu-img">
                                <img src="{{ asset('Front/img/imageMenu2.jpg') }}" alt="Image">
                            </div>
                            <div class="menu-text">
                                <h3><span>{{ pdt.nomProduitPlat }}</span> <strong> {{ pdt.Prix }}</strong></h3>
                                <p> {{ pdt.DescProduitPlat }}</p>
                            </div>
                        </div>
                    {% endfor %}
                    <div class="pagination">
                        <div class="row-cols-sm-4">
                            {{ knp_pagination_render(listPdt) }}
                        </div>
                    </div>


                </div>
                <div class="col-lg-5 d-none d-lg-block">
                    <img src="{{ asset('Front/img/imagefood2.jpg') }}" alt="Image">
                </div>
            </div>
        </div>

    </div>
{% endblock %}

templates/Front/about.html.twig
{% extends 'base.html.twig' %}
{% block bodyMenu %}
    <!-- Page Header Start -->
    <div class="page-header mb-0">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>About Us</h2>
                </div>
                <div class="col-12">
                    <a href="">Home</a>
                    <a href="">About Us</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <!-- About Start -->
    <div class="about">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6">
                    <div class="about-img">
                        <img src="{{ asset('Front/img/about.jpg') }}" alt="Image">
                        <button type="button" class="btn-play" data-toggle="modal" data-src="{{ asset('https://www.youtube.com/embed/DWRcNpR6Kdc') }}" data-target="#videoModal">
                            <span></span>
                        </button>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="about-content">
                        <div class="section-header">
                            <p>About Us</p>
                            <h2>Cooking Since 1990</h2>
                        </div>
                        <div class="about-text">
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem.
                            </p>
                            <p>
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus nec pretium mi. Curabitur facilisis ornare velit non vulputate. Aliquam metus tortor, auctor id gravida condimentum, viverra quis sem. Curabitur non nisl nec nisi scelerisque maximus. Aenean consectetur convallis porttitor. Aliquam interdum at lacus non blandit.
                            </p>
                            <a class="btn custom-btn" href="">Book A Table</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->
    <!-- Video Modal Start-->
    <div class="modal fade" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <!-- 16:9 aspect ratio -->
                    <div class="embed-responsive embed-responsive-16by9">
                        <iframe class="embed-responsive-item" src="" id="video"  allowscriptaccess="always" allow="autoplay"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Video Modal End -->

    <hr data-content="AND" class="hr-text">
    <!-- Team Start -->
    <div class="team">
        <div class="container">
            <div class="section-header text-center">
                <p>Our Team</p>
                <h2>DevFive</h2>
            </div>
            <div class="row">
                <div class="col-lg-3 col-md-6">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{{ asset('Front/img/eya.jpg') }}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Eya SAID</h2>
                            <p>CEO, Co Founder</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{{ asset('Front/img/nour.jpg') }}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Nour HAMMAMI</h2>
                            <p>Master Chef</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{{ asset('Front/img/ines.PNG') }}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Ines HABA</h2>
                            <p>Master Chef</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{{ asset('Front/img/amen.jpg') }}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Amen GABSI</h2>
                            <p>Master Chef</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{{ asset('Front/img/badi.jpg') }}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Badi GUEDOUAR</h2>
                            <p>Master Chef</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="team-item">
                        <div class="team-img">
                            <img src="{{ asset('Front/img/yassine.png') }}" alt="Image">
                            <div class="team-social">
                                <a href=""><i class="fab fa-twitter"></i></a>
                                <a href=""><i class="fab fa-facebook-f"></i></a>
                                <a href=""><i class="fab fa-linkedin-in"></i></a>
                                <a href=""><i class="fab fa-instagram"></i></a>
                            </div>
                        </div>
                        <div class="team-text">
                            <h2>Yassine SELLAMI</h2>
                            <p>Master Chef</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Team End -->

{% endblock %}

templates/Front/booking.html.twig
{% extends 'base.html.twig' %}
{% block bodyMenu %}
    <!-- Page Header Start -->
    <div class="page-header mb-0">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Rservez votre Table</h2>
                </div>
                <div class="col-12">
                    <a href="">Accueil</a>
                    <a href="">Reservation</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->


    <!-- Booking Start -->
    <div class="booking">
        <div class="container-fluid">
            <div class="row align-items-center">
                <div class="col-lg-7">
                    <div class="booking-content">
                        <div class="section-header">
                            <H1>Reserver une Table</H1>
                            <div class="menu-img">
                                <img src="{{ asset('Front/img/reser.jpg') }}" alt="Image">
                            </div>
                        </div>
                        <div class="about-text">
                            <p>
                             Reservez votre place
                            </p>
                        </div>
                    </div>
                </div>

                <div class="col-lg-5">
                    <div class="booking-form">
                    {% block booking %}  {% endblock %}

                </div>
            </div>
        </div>
    </div>
    <!-- Booking End -->
{% endblock %}

templates/Front/index.html.twig
{% extends 'base.html.twig' %}
{% block bodyMenu %}
    <!-- Carousel Start -->
    <div class="carousel">
        <div class="container-fluid">
            <div class="owl-item">

                <div class="carousel-item">
                    <div class="carousel-img">
                        <img src="{{ asset('Front/img/carousel-1.jpg') }}" alt="Image">

                    </div>
                    <div class="carousel-text">
                        <h1> Pour les amateurs de la <span>bonne bouffe</span>, Chez Dma9 vous trouverez votre plaisir</h1>
                        <p>

                        </p>
                        <div class="carousel-btn">
                            <a href="{{ path("category_front") }}" class="btn custom-btn" href="">Visiter la boutique en ligne</a>
                            <a href="{{ path("reservation_new") }}" class="btn custom-btn" href="">Reserver une table</a>
                        </div>
                    </div>
                </div>







            </div>
        </div>
    </div>
    <!-- Carousel End -->

{% endblock %}

templates/Front/menu.html.twig
{% extends '/base.html.twig' %}
{% block bodyMenu %}
    <!-- Menu Start -->
    <div class="page-header mb-0">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Découvrez notre menu</h2>
                </div>
                <div class="col-12">
                    <a href="">Home</a>
                </div>
            </div>
        </div>
    </div>
    <div class="menu">
        <div class="container">
            <div class="section-header text-center">
                <p>le Menu du restaurant :</p>

                <h2>{{ restaurant.nomRestaurant }}</h2>
            </div>
            <div class="menu-tab">
                <ul class="nav nav-pills justify-content-center">

                        {% for cat in categorie %}
                    <li class="nav-item">
                        <div class="nav-link" >
                            <a href="{{ path('showProduitPlatCategorie', {'id_restaurant':restaurant.getIdRestaurant(),'id_categorie': cat.getIdCategorie()  }) }}">{{cat.nomCategorie}} </a>

                        </div>

                        </li>
                        {% endfor %}
                </ul>
                {% block DetailMenu%}       {% endblock %}




            </div>
        </div>
    </div>
    <!-- Menu End -->

{% endblock %}

templates/Front/offreTravail.html.twig
{% extends 'base.html.twig' %}
{% block bodyMenu %}
<!-- Page Header Start -->
<div class="page-header">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2>Master Chef</h2>
            </div>
            <div class="col-12">
                <a href="">Home</a>
                <a href="">Job offers</a>
            </div>
        </div>
    </div>
</div>
<!-- Page Header End -->

<div  >
    <table class="table">
        <thead>
        <tr>

            <th>Titre</th>
            <th>Description</th>
            <th>Restaurant </th>
            <th>Restaurant owner</th>

        </tr>
        </thead>
        <tbody>
        {% for offre_travail in offre_travails %}
            <tr>

                <td>{{ offre_travail.titre }}</td>
                <td>{{ offre_travail.description }}</td>
                <td>{{ offre_travail.restaurant }}</td>
                <td>{{ offre_travail.user.prenom ~" "~ offre_travail.user.nom }}</td>


            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

</div>





{% endblock %}

templates/Front/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block bodyMenu %}
    <div class="page-header mb-0">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Profil</h2>
                </div>
                <div class="col-12">
                    <a href="">Home</a>
                    <a href="">Profil</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Nom</th>
            <th>Prenom</th>
            <th>Date</th>
            <th>Sexe</th>
            <th>Numero_tele</th>
            <th>Email</th>
            <th>Roles</th>
            <th>Password</th>

        </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.date ? user.date|date('Y-m-d') : '' }}</td>
                <td>{{ user.sexe }}</td>
                <td>{{ user.numeroTele }}</td>
                <td>{{ user.email }}</td>
                <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
                <td>{{ user.password|length }}</td>
                <td>
                    <a class="btn btn-primary" href="{{ path('user_show_', {'id': user.id}) }}">show</a>
                    <a class="btn btn-primary" href="{{ path('user_edit_', {'id': user.id}) }}">edit</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


{% endblock %}

templates/Front/profil1.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!{% endblock %}

{% block bodyMenu %}
    <div class="page-header mb-0">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2>Profil</h2>
                </div>
                <div class="col-12">
                    <a href="">Home</a>
                    <a href="">Profil</a>
                </div>
            </div>
        </div>
    </div>
    <!-- Page Header End -->

    <h1>User</h1>

    <table class="table">
        <tbody>
        <tr>
            <th>Id</th>
            <td>{{ user.id }}</td>
        </tr>
        <tr>
            <th>Nom</th>
            <td>{{ user.nom }}</td>
        </tr>
        <tr>
            <th>Prenom</th>
            <td>{{ user.prenom }}</td>
        </tr>
        <tr>
            <th>Date</th>
            <td>{{ user.date ? user.date|date('Y-m-d') : '' }}</td>
        </tr>
        <tr>
            <th>Sexe</th>
            <td>{{ user.sexe }}</td>
        </tr>
        <tr>
            <th>Numero_tele</th>
            <td>{{ user.numeroTele }}</td>
        </tr>
        <tr>
            <th>Email</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>Roles</th>
            <td>{{ user.roles ? user.roles|json_encode : '' }}</td>
        </tr>
        <tr>
            <th>Password</th>
            <td>{{ user.password}}</td>
        </tr>
        <tr>
            <th>Image</th>
            <td>{{ user.image}}</td>
        </tr>
        </tbody>
    </table>


    <a href="{{ path('user_edit_', {'id': user.id}) }}">edit</a>


{% endblock %}